import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  playerFullScreen: {
    flex: 1,
    paddingHorizontal: 24,
    justifyContent: 'space-between',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 56,
    width: '100%',
    zIndex: 10,
  },
  closeButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    color: '#8B5CF6',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 2,
    textAlign: 'center',
  },
  headerPlaceholder: {
    width: 40,
  },
  artworkContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 16,
    width: '100%',
    zIndex: 10,
  },
  artworkShadowWrapper: {
    width: '100%',
    maxWidth: 320,
    aspectRatio: 1,
    borderRadius: 24,
    backgroundColor: '#161722',
    shadowColor: '#8B5CF6',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.35,
    shadowRadius: 18,
    elevation: 10,
  },
  artwork: {
    width: '100%',
    height: '100%',
    borderRadius: 24,
  },
  bottomSection: {
    width: '100%',
    marginBottom: 8,
    zIndex: 10,
  },
  trackDetails: {
    alignItems: 'flex-start',
    width: '100%',
    marginBottom: 20,
    paddingHorizontal: 4,
  },
  trackTitle: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 6,
  },
  trackArtist: {
    color: '#E2E3E9',
    fontSize: 16,
    fontWeight: '500',
  },
  liveLyricContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    paddingVertical: 2,
    paddingHorizontal: 0,
    backgroundColor: 'transparent',
    width: '100%',
  },
  liveLyricText: {
    color: 'rgba(255, 255, 255, 0.75)',
    fontSize: 14,
    fontWeight: '500',
    letterSpacing: 0.1,
    flex: 1,
  },


  footerRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 18,
  },
  footerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: 'rgba(22, 23, 34, 0.6)',
    borderWidth: 1,
    borderColor: 'rgba(44, 45, 60, 0.6)',
  },
  footerButtonText: {
    color: '#8E8F9E',
    fontSize: 13,
    fontWeight: '600',
  },
  lyricsSheetContent: {
    height: '75%',
    backgroundColor: '#12131A',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    paddingHorizontal: 20,
    overflow: 'hidden',
  },
  lyricsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  lyricsTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '800',
  },
  lyricsTrackSub: {
    color: '#A78BFA',
    fontSize: 13,
    fontWeight: '600',
    marginTop: 2,
  },
  lyricsCloseBtn: {
    padding: 6,
  },
  lyricsScrollView: {
    flex: 1,
  },
  lyricsScrollContent: {
    paddingVertical: 12,
    paddingHorizontal: 6,
  },
  lyricsBodyText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 34,
    letterSpacing: 0.2,
  },
  lyricLineText: {
    color: 'rgba(255, 255, 255, 0.35)',
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 34,
    marginBottom: 12,
  },
  lyricLineActiveText: {
    color: '#FFFFFF',
    fontSize: 23,
    fontWeight: '900',
    lineHeight: 38,
    backgroundColor: 'rgba(139, 92, 246, 0.15)',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
    textShadowColor: 'rgba(167, 139, 250, 0.6)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 10,
  },
  lyricsLoadingContainer: {
    paddingVertical: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  lyricsLoadingText: {
    color: '#8E8F9E',
    fontSize: 14,
    marginTop: 12,
    fontWeight: '500',
  },
  emptyLyricsContainer: {
    paddingVertical: 50,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  emptyLyricsIconCircle: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: 'rgba(139, 92, 246, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.2)',
  },
  emptyLyricsTitle: {
    color: '#E2E3E9',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 8,
  },
  emptyLyricsSub: {
    color: '#8E8F9E',
    fontSize: 13,
    textAlign: 'center',
    paddingHorizontal: 20,
    lineHeight: 18,
  },
  addLyricsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: '#8B5CF6',
    marginTop: 18,
  },
  addLyricsBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  queueListContent: {
    paddingVertical: 12,
    paddingHorizontal: 0,
    zIndex: 10,
  },
  queueItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 6,
    marginBottom: 6,
    backgroundColor: 'transparent',
  },
  queueItemActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 8,
  },
  queueItemMainContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  queueArtwork: {
    width: 44,
    height: 44,
    borderRadius: 4,
    marginRight: 14,
  },
  queueDetails: {
    flex: 1,
  },
  queueTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  queueTitle: {
    color: '#E2E3E9',
    fontSize: 15,
    fontWeight: '600',
    flex: 1,
  },
  queueTextActive: {
    color: '#A78BFA',
  },
  queueArtist: {
    color: '#8E8F9E',
    fontSize: 13,
  },
  rightActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  removeButton: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  activePlayCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 4,
  },
  emptyWrapper: {
    paddingVertical: 60,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    zIndex: 10,
  },
  emptyIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(139, 92, 246, 0.05)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.15)',
  },
  emptyText: {
    color: '#8E8F9E',
    fontSize: 15,
    fontWeight: '600',
    marginTop: 12,
  },
  emptySubText: {
    color: '#5F6070',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 6,
    paddingHorizontal: 20,
  },
  bottomSheetOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    zIndex: 999,
  },
  bottomSheetBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#000000',
  },
  bottomSheetContent: {
    height: '66%',
    backgroundColor: '#12131A',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
    paddingHorizontal: 20,
    overflow: 'hidden',
  },
  bottomSheetHandleWrapper: {
    width: '100%',
    alignItems: 'center',
    paddingVertical: 12,
  },
  bottomSheetHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  bottomSheetHeader: {
    height: 48,
    justifyContent: 'center',
    width: '100%',
    marginBottom: 10,
    paddingHorizontal: 4,
  },
  bottomSheetTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '800',
  },
});

export default styles;

