import { StyleSheet, Dimensions } from 'react-native';

const { height: SCREEN_HEIGHT } = Dimensions.get('window');

const styles = StyleSheet.create({
  bottomSheetOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    zIndex: 1000,
  },
  bottomSheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(9, 10, 15, 0.75)',
  },
  bottomSheetContent: {
    backgroundColor: '#10111A',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderColor: '#26273B',
    borderBottomWidth: 0,
    maxHeight: SCREEN_HEIGHT * 0.88,
    minHeight: SCREEN_HEIGHT * 0.45,
    overflow: 'hidden',
  },
  bottomSheetHandleWrapper: {
    width: '100%',
    alignItems: 'center',
    paddingVertical: 10,
  },
  bottomSheetHandle: {
    width: 44,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#3E4059',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.3,
  },
  headerCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  nowPlayingCard: {
    marginHorizontal: 16,
    marginBottom: 14,
    padding: 12,
    borderRadius: 14,
    backgroundColor: 'rgba(139, 92, 246, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.25)',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: '#A78BFA',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  nowPlayingContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  nowPlayingArtwork: {
    width: 46,
    height: 46,
    borderRadius: 8,
    marginRight: 12,
  },
  nowPlayingDetails: {
    flex: 1,
    justifyContent: 'center',
  },
  nowPlayingTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  nowPlayingArtist: {
    fontSize: 13,
    color: '#8E8F9E',
    marginTop: 2,
  },
  nowPlayingActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  playPauseCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#8B5CF6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  upcomingHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginBottom: 8,
    marginTop: 2,
  },
  clearQueueBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.25)',
  },
  clearQueueText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#EF4444',
  },
  listContent: {
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  queueItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginBottom: 6,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    height: 64,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  queueItemDragging: {
    backgroundColor: '#201D33',
    borderColor: '#8B5CF6',
    shadowColor: '#8B5CF6',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.45,
    shadowRadius: 10,
    elevation: 12,
    zIndex: 999,
  },
  queueItemMainContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    height: '100%',
    overflow: 'hidden',
  },
  queueItemArtwork: {
    width: 42,
    height: 42,
    borderRadius: 6,
    marginRight: 12,
  },
  queueItemDetails: {
    flex: 1,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  queueItemTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#E2E3E9',
  },
  queueItemArtist: {
    fontSize: 12,
    color: '#8E8F9E',
    marginTop: 2,
  },
  actionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    height: '100%',
    gap: 2,
  },
  quickMoveBtn: {
    width: 28,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  quickMoveBtnDisabled: {
    opacity: 0.2,
  },
  removeBtn: {
    width: 32,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dragHandle: {
    width: 36,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: 4,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 36,
    paddingHorizontal: 24,
  },
  emptyIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(139, 92, 246, 0.08)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.2)',
  },
  emptyTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#E2E3E9',
    textAlign: 'center',
  },
  emptySub: {
    fontSize: 12,
    color: '#8E8F9E',
    marginTop: 6,
    textAlign: 'center',
    lineHeight: 18,
    paddingHorizontal: 12,
  },
  previousHeaderBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 12,
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.06)',
  },
  previousTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: '#6B6C80',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  previousListContainer: {
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  previousItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginBottom: 4,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.015)',
    height: 52,
    opacity: 0.65,
  },
  previousItemArtwork: {
    width: 36,
    height: 36,
    borderRadius: 6,
    marginRight: 12,
  },
  previousItemTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#A0A1B0',
  },
  previousItemArtist: {
    fontSize: 11,
    color: '#6B6C80',
    marginTop: 1,
  },
});

export default styles;
