import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  listContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  tabsContainer: {
    flexDirection: 'row',
    backgroundColor: '#12131A',
    borderRadius: 12,
    padding: 4,
    marginTop: 8,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#1F202E',
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 8,
  },
  tabButtonActive: {
    backgroundColor: '#1C1D2A',
    borderWidth: 1,
    borderColor: '#3B3D54',
  },
  tabLabel: {
    color: '#8E8F9E',
    fontSize: 14,
    fontWeight: '600',
  },
  tabLabelActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  searchSection: {
    marginTop: 12,
    marginBottom: 16,
    width: '100%',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#12131A',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#1F202E',
    paddingHorizontal: 12,
    height: 48,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    color: '#E2E3E9',
    fontSize: 14,
    height: '100%',
  },
  localActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 8,
    width: '100%',
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(139, 92, 246, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.2)',
    borderRadius: 12,
    paddingVertical: 10,
    gap: 6,
  },
  actionButtonText: {
    color: '#E2E3E9',
    fontSize: 12,
    fontWeight: '600',
  },
  resetButton: {
    flex: 0,
    width: 44,
    borderColor: 'rgba(239, 68, 68, 0.2)',
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
  },
  queueHeader: {
    color: '#5F6070',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.5,
    marginTop: 24,
    marginBottom: 12,
  },
  queueItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 6,
    marginBottom: 6,
    backgroundColor: 'transparent',
  },
  itemMainContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  addToQueueButton: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  rightActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  queueItemActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 8,
  },
  queueItemDisabled: {
    opacity: 0.5,
  },
  queueArtwork: {
    width: 44,
    height: 44,
    borderRadius: 4,
    marginRight: 14,
  },
  queueDetails: {
    flex: 1,
  },
  queueTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  queueTitle: {
    color: '#E2E3E9',
    fontSize: 15,
    fontWeight: '600',
    flex: 1,
  },
  queueTextActive: {
    color: '#A78BFA',
  },
  queueArtist: {
    color: '#8E8F9E',
    fontSize: 13,
  },
  playingIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(139, 92, 246, 0.12)',
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.3)',
    marginRight: 6,
  },
  playingIndicatorText: {
    color: '#8B5CF6',
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  loadingWrapper: {
    paddingVertical: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: '#5F6070',
    fontSize: 13,
    marginTop: 12,
  },
  emptyWrapper: {
    paddingVertical: 40,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  emptyIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(139, 92, 246, 0.05)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.1)',
  },
  emptyText: {
    color: '#8E8F9E',
    fontSize: 15,
    fontWeight: '600',
    marginTop: 12,
  },
  emptySubText: {
    color: '#5F6070',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 6,
    paddingHorizontal: 20,
  },
  driveHeaderBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#161722',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#2C2D3C',
    padding: 16,
    marginBottom: 20,
  },
  driveStatusCol: {
    flex: 1,
  },
  driveStatusIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  driveStatusText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    marginLeft: 8,
  },
  driveInfoText: {
    color: '#8E8F9E',
    fontSize: 12,
    marginLeft: 28,
  },
  driveActionsCol: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  driveActionBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
  },
  driveUploadBtn: {
    backgroundColor: '#8B5CF6',
    borderColor: '#A78BFA',
  },
  driveRefreshBtn: {
    backgroundColor: '#232433',
    borderColor: '#3B3D54',
  },
  driveDisconnectBtn: {
    backgroundColor: '#232433',
    borderColor: '#3B3D54',
  },
  driveConnectCard: {
    backgroundColor: '#161722',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#2C2D3C',
    padding: 20,
    marginBottom: 20,
  },
  driveCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  driveIconWrapper: {
    width: 50,
    height: 50,
    borderRadius: 12,
    backgroundColor: 'rgba(139, 92, 246, 0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.2)',
  },
  driveCardTitleCol: {
    flex: 1,
  },
  driveCardTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  driveCardSubtitle: {
    color: '#8E8F9E',
    fontSize: 12,
    marginTop: 2,
  },
  driveDescriptionText: {
    color: '#8E8F9E',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 20,
  },
  devWarningBox: {
    flexDirection: 'row',
    backgroundColor: 'rgba(245, 158, 11, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.2)',
    borderRadius: 10,
    padding: 12,
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  devWarningText: {
    flex: 1,
    color: '#F59E0B',
    fontSize: 12,
    lineHeight: 18,
  },
  driveConnectBtn: {
    flexDirection: 'row',
    backgroundColor: '#8B5CF6',
    borderRadius: 12,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#8B5CF6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  driveConnectBtnDisabled: {
    backgroundColor: '#2A2B3D',
    shadowOpacity: 0,
    elevation: 0,
  },
  driveConnectBtnText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },

  // Estilos específicos de las listas de reproducción (Playlists)
  playlistDetailContainer: {
    flex: 1,
  },
  playlistBackBtnContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 16,
    gap: 6,
  },
  playlistBackBtnText: {
    color: '#8E8F9E',
    fontSize: 14,
    fontWeight: '600',
  },
  playlistHeroCard: {
    flexDirection: 'row',
    backgroundColor: '#161722',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 20,
    padding: 16,
    marginBottom: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  playlistHeroArtworkContainer: {
    width: 90,
    height: 90,
    borderRadius: 14,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  playlistHeroDetails: {
    flex: 1,
    marginLeft: 16,
    justifyContent: 'center',
  },
  playlistHeroName: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 22,
    marginBottom: 4,
  },
  playlistHeroCount: {
    color: '#8E8F9E',
    fontSize: 13,
    marginBottom: 12,
  },
  playlistHeroPlayBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#8B5CF6',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 16,
    alignSelf: 'flex-start',
    gap: 4,
    shadowColor: '#8B5CF6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 3,
  },
  playlistHeroPlayBtnDisabled: {
    backgroundColor: '#2A2B3D',
    shadowOpacity: 0,
    elevation: 0,
  },
  playlistHeroPlayBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  playlistsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
    marginBottom: 16,
    paddingHorizontal: 8,
  },
  playlistsTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  createPlaylistToggleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(139, 92, 246, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.2)',
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 12,
    gap: 4,
  },
  createPlaylistToggleText: {
    color: '#A78BFA',
    fontSize: 12,
    fontWeight: '600',
  },
  createPlaylistInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#161722',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    paddingLeft: 12,
    paddingRight: 4,
    height: 48,
    marginBottom: 16,
  },
  createPlaylistInput: {
    flex: 1,
    color: '#E2E3E9',
    fontSize: 14,
    height: '100%',
  },
  createPlaylistBtn: {
    backgroundColor: '#8B5CF6',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  createPlaylistBtnDisabled: {
    backgroundColor: '#2A2B3D',
  },
  createPlaylistBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  playlistRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#161722',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.04)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 1,
  },
  playlistRowMain: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  playlistArtworkContainer: {
    width: 48,
    height: 48,
    borderRadius: 10,
    marginRight: 14,
    overflow: 'hidden',
  },
  playlistArtworkImage: {
    width: '100%',
    height: '100%',
  },
  playlistIconWrapperGradient: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  playlistRowDetails: {
    flex: 1,
  },
  playlistRowName: {
    color: '#E2E3E9',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 4,
  },
  playlistRowSub: {
    color: '#8E8F9E',
    fontSize: 13,
  },
  playlistRowActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  playlistPlayRowBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#8B5CF6',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#8B5CF6',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 2,
  },
  playlistPlayRowBtnDisabled: {
    backgroundColor: '#1E1F2E',
    shadowOpacity: 0,
    elevation: 0,
  },
  playlistDeleteRowBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteTrackFromPlaylistBtn: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },

  // Estilos de modal para Opciones de pista y Selector de lista de reproducción
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#0C0D14',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderColor: '#1F202E',
    padding: 24,
    paddingBottom: 40,
    alignItems: 'center',
    width: '100%',
  },
  modalTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
    width: '100%',
  },
  modalSubtitle: {
    color: '#8E8F9E',
    fontSize: 14,
    marginTop: 4,
    textAlign: 'center',
    width: '100%',
  },
  modalDivider: {
    height: 1,
    backgroundColor: '#1F202E',
    width: '100%',
    marginVertical: 16,
  },
  modalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#12131A',
    borderWidth: 1,
    borderColor: '#1F202E',
    borderRadius: 14,
    width: '100%',
    paddingVertical: 14,
    marginBottom: 10,
    gap: 8,
  },
  modalOptionText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  modalCancelOption: {
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
    borderColor: 'rgba(239, 68, 68, 0.2)',
    marginTop: 6,
  },
  modalCancelText: {
    color: '#EF4444',
    fontSize: 14,
    fontWeight: '700',
  },
  emptyPlaylistsModalText: {
    color: '#5F6070',
    fontSize: 13,
    textAlign: 'center',
    marginVertical: 16,
  },
  playlistPickerOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#12131A',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(31, 32, 46, 0.8)',
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 8,
    width: '100%',
    gap: 8,
  },
  playlistPickerName: {
    flex: 1,
    color: '#E2E3E9',
    fontSize: 14,
    fontWeight: '600',
  },
  playlistPickerCount: {
    color: '#5F6070',
    fontSize: 12,
  },
  inlineCreateWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#12131A',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#1F202E',
    paddingLeft: 12,
    paddingRight: 4,
    height: 44,
    width: '100%',
    marginTop: 4,
  },
  inlineCreateInput: {
    flex: 1,
    color: '#E2E3E9',
    fontSize: 13,
    height: '100%',
  },
  inlineCreateBtn: {
    backgroundColor: '#8B5CF6',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  inlineCreateBtnDisabled: {
    backgroundColor: '#2A2B3D',
  },
  inlineCreateBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
});

export default styles;
