import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  overlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 9999,
    flexDirection: 'row',
  },
  backdrop: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#000000',
  },
  drawer: {
    width: 290,
    height: '100%',
    backgroundColor: '#0C0D14',
    borderRightWidth: 1,
    borderRightColor: '#1F202E',
    paddingHorizontal: 20,
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 16,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  logoContainer: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: 'rgba(139, 92, 246, 0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.2)',
  },
  logoImage: {
    width: 32,
    height: 32,
  },
  headerTextContainer: {
    justifyContent: 'center',
  },
  title: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 2,
  },
  subtitle: {
    color: '#5F6070',
    fontSize: 10,
    fontWeight: '600',
    marginTop: 2,
  },
  divider: {
    height: 1,
    backgroundColor: '#1A1C29',
    marginBottom: 25,
  },
  sectionHeader: {
    color: '#4B4D63',
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 1.5,
    marginBottom: 12,
    paddingLeft: 8,
  },
  menuList: {
    gap: 8,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: 'transparent',
    position: 'relative',
    overflow: 'hidden',
  },
  menuItemActive: {
    backgroundColor: 'rgba(139, 92, 246, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.15)',
  },
  menuItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  menuItemTextCol: {
    marginLeft: 12,
    flex: 1,
  },
  menuItemLabel: {
    color: '#8E8F9E',
    fontSize: 14,
    fontWeight: '600',
  },
  menuItemLabelActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  menuItemDesc: {
    color: '#5F6070',
    fontSize: 10,
    marginTop: 2,
  },
  activeIndicator: {
    width: 3,
    height: 16,
    borderRadius: 1.5,
    backgroundColor: '#8B5CF6',
    position: 'absolute',
    left: 0,
    top: '50%',
    marginTop: -8,
  },
  footer: {
    borderTopWidth: 1,
    borderTopColor: '#1A1C29',
    paddingTop: 15,
    gap: 12,
  },
  settingsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 8,
  },
  settingsLabel: {
    color: '#8E8F9E',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 10,
  },
  versionText: {
    color: '#3F4052',
    fontSize: 10,
    fontFamily: 'monospace',
    paddingLeft: 8,
  },
});

export default styles;
